# Nixpacks configuration for SwellSense backend
[phases.setup]
nixPkgs = ["python39", "python39Packages.pip"]

[phases.install]
cmds = ["pip install -r backend/requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "./start.sh"
